---
name: MetaStore
version: 0.29
author:
  - Zahatski Aliaksandr zag@cpan.org
abstract: Set of classes for multiuser web applications.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Archive::Zip: 1.16
  Data::UUID: 0.11
  HTML::WebDAO: 0.80
  IO::Zlib: 1.04
  JSON: 2.07
  MIME::Base64: 3.07
  Objects::Collection: 0.02
  Template: 2.14
  XML::Flow: 0.82
provides:
  MetaStore:
    file: lib/MetaStore.pm
    version: 0.29
  MetaStore::Auth:
    file: lib/MetaStore/Auth.pm
    version: 0.01
  MetaStore::Auth::Group:
    file: lib/MetaStore/Auth/Group.pm
    version: 0.01
  MetaStore::Auth::User:
    file: lib/MetaStore/Auth/User.pm
    version: 0.01
  MetaStore::Auth::UserGuest:
    file: lib/MetaStore/Auth/UserGuest.pm
  MetaStore::Base:
    file: lib/MetaStore/Base.pm
    version: 0.01
  MetaStore::Cmetalinks:
    file: lib/MetaStore/Cmetalinks.pm
  MetaStore::Cmetatags:
    file: lib/MetaStore/Cmetatags.pm
  MetaStore::Component:
    file: lib/MetaStore/Component.pm
    version: 0.01
  MetaStore::Config:
    file: lib/MetaStore/Config.pm
    version: 0.2
  MetaStore::DAOItem:
    file: lib/MetaStore/DAOItem.pm
    version: 0.01
  MetaStore::IsAuthed:
    file: lib/MetaStore/IsAuthed.pm
  MetaStore::Item:
    file: lib/MetaStore/Item.pm
    version: 0.01
  MetaStore::Kern:
    file: lib/MetaStore/Kern.pm
  MetaStore::Links:
    file: lib/MetaStore/Links.pm
    version: 0.01
  MetaStore::Mem:
    file: lib/MetaStore/Mem.pm
    version: 0.01
  MetaStore::MemnotUnique:
    file: lib/MetaStore/MemnotUnique.pm
    version: 0.01
  MetaStore::Response:
    file: lib/MetaStore/Response.pm
  MetaStore::StoreDir:
    file: lib/MetaStore/StoreDir.pm
  MetaStore::Users:
    file: lib/MetaStore/Users.pm
    version: 0.01
  MetaStore::XMLStream:
    file: lib/MetaStore/XMLStream.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
