---
abstract: 'Set of classes for multiuser web applications.'
author:
  - 'Zahatski Aliaksandr zag@cpan.org'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3624'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MetaStore
provides:
  MetaStore:
    file: lib/MetaStore.pm
    version: 0.55
  MetaStore::Auth:
    file: lib/MetaStore/Auth.pm
    version: 0.01
  MetaStore::Auth::Group:
    file: lib/MetaStore/Auth/Group.pm
    version: 0.01
  MetaStore::Auth::User:
    file: lib/MetaStore/Auth/User.pm
    version: 0.01
  MetaStore::Auth::UserGuest:
    file: lib/MetaStore/Auth/UserGuest.pm
  MetaStore::Base:
    file: lib/MetaStore/Base.pm
    version: 0.01
  MetaStore::Cmetalinks:
    file: lib/MetaStore/Cmetalinks.pm
  MetaStore::Cmetatags:
    file: lib/MetaStore/Cmetatags.pm
  MetaStore::Component:
    file: lib/MetaStore/Component.pm
    version: 0.01
  MetaStore::Config:
    file: lib/MetaStore/Config.pm
    version: 0.2
  MetaStore::DAOItem:
    file: lib/MetaStore/DAOItem.pm
    version: 0.01
  MetaStore::IsAuthed:
    file: lib/MetaStore/IsAuthed.pm
  MetaStore::Item:
    file: lib/MetaStore/Item.pm
    version: 0.01
  MetaStore::Kern:
    file: lib/MetaStore/Kern.pm
  MetaStore::Links:
    file: lib/MetaStore/Links.pm
    version: 0.01
  MetaStore::Response:
    file: lib/MetaStore/Response.pm
  MetaStore::StoreDir:
    file: lib/MetaStore/StoreDir.pm
  MetaStore::Users:
    file: lib/MetaStore/Users.pm
    version: 0.01
requires:
  Archive::Zip: 1.16
  Collection: 0.49
  Data::UUID: 0.11
  IO::Zlib: 1.04
  JSON: 2.07
  MIME::Base64: 3.07
  Template: 2.14
  WebDAO: 2.0
  XML::Flow: 0.86
resources:
  license: http://dev.perl.org/licenses/
version: 0.55
